application: daniel-personal-website
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/(.+)
  static_files: static/\1
  upload: static/(.*)

- url: /bower_components/(.+)
  static_files: bower_components/\1
  upload: bower_components/(.*)

- url: /api/(.+)
  script: api.app

- url: /developer_gender
  static_files: developer_gender/index.html
  upload: developer_gender/index.html

- url: /developer_gender/(.+)
  static_files: developer_gender/\1
  upload: developer_gender/(.+)

- url: /(.*)
  static_files: static/pages/index.html
  upload: static/pages/index.html
