application: daniel-personal-website
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/(.+)
  static_files: static/\1
  upload: static/(.*)

- url: /bower_components/(.+)
  static_files: bower_components/\1
  upload: bower_components/(.*)

- url: /api/(.+)
  script: api.app

- url: /.*
  script: main.app
