application: daniel-personal-website
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /s/(.+)
  static_files: static/\1
  upload: static/(.*)
  
- url: /(.*)
  static_files: static/pages/index.html
  upload: static/pages/index.html